version: '3.1'

services:

  node-web:
    build: .
    image: node-web:latest
    # command: npm run start:migrate:deploy
    # restart: always
    volumes:
      - .:/usr/app/
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SALT_ROUNDS: ${SALT_ROUNDS}
      SECRET_KEY: ${SECRET_KEY}
      SECRET_KEY_AES: ${SECRET_KEY_AES}
      PORT: ${PORT}
    networks:
      - app-tier
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app-tier
    ports:
      - 3306:3306

  adminer:
    image: adminer:4.7
    restart: always
    networks:
      - app-tier
    ports:
      - 8080:8080
    depends_on:
      - mysql

networks:
  app-tier:
    driver: bridge
