version: '3'

services:

  runsys:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SALT_ROUNDS: ${SALT_ROUNDS}
      SECRET_KEY: ${SECRET_KEY}
      SECRET_KEY_AES: ${SECRET_KEY_AES}
      PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mysql
    networks:
      - app_net

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - app_net

  adminer:
    image: adminer:latest
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DEFAULT_USERNAME: ${MYSQL_USER}
      ADMINER_DEFAULT_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      - app_net

volumes:
  mysql:


networks:
  app_net:
    driver: bridge
